# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v1_0/associated_file.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3sapient_msg/bsi_flex_335_v1_0/associated_file.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\x1a\x1fsapient_msg/proto_options.proto\"Z\n\x0e\x41ssociatedFile\x12\x1b\n\x04type\x18\x01 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01(\x01H\x00\x88\x01\x01\x12\x1a\n\x03url\x18\x02 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01(\x01H\x01\x88\x01\x01\x42\x07\n\x05_typeB\x06\n\x04_urlB/\n\x16uk.gov.dstl.sapientmsgB\x13\x41ssociatedFileProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.associated_file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026uk.gov.dstl.sapientmsgB\023AssociatedFileProtoP\001'
  _globals['_ASSOCIATEDFILE'].fields_by_name['type']._options = None
  _globals['_ASSOCIATEDFILE'].fields_by_name['type']._serialized_options = b'\212\265\030\004\010\001(\001'
  _globals['_ASSOCIATEDFILE'].fields_by_name['url']._options = None
  _globals['_ASSOCIATEDFILE'].fields_by_name['url']._serialized_options = b'\212\265\030\004\010\001(\001'
  _globals['_ASSOCIATEDFILE']._serialized_start=119
  _globals['_ASSOCIATEDFILE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
