# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v1_0/velocity.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sapient_msg/bsi_flex_335_v1_0/velocity.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\x1a\x1fsapient_msg/proto_options.proto\"\xce\x02\n\x0b\x45NUVelocity\x12!\n\teast_rate\x18\x01 \x01(\x01\x42\t\x8a\xb5\x18\x05\x08\x01\"\x01XH\x00\x88\x01\x01\x12\"\n\nnorth_rate\x18\x02 \x01(\x01\x42\t\x8a\xb5\x18\x05\x08\x01\"\x01YH\x01\x88\x01\x01\x12\x1d\n\x07up_rate\x18\x03 \x01(\x01\x42\x07\x8a\xb5\x18\x03\"\x01ZH\x02\x88\x01\x01\x12&\n\x0f\x65\x61st_rate_error\x18\x04 \x01(\x01\x42\x08\x8a\xb5\x18\x04\"\x02\x65XH\x03\x88\x01\x01\x12\'\n\x10north_rate_error\x18\x05 \x01(\x01\x42\x08\x8a\xb5\x18\x04\"\x02\x65YH\x04\x88\x01\x01\x12$\n\rup_rate_error\x18\x06 \x01(\x01\x42\x08\x8a\xb5\x18\x04\"\x02\x65ZH\x05\x88\x01\x01\x42\x0c\n\n_east_rateB\r\n\x0b_north_rateB\n\n\x08_up_rateB\x12\n\x10_east_rate_errorB\x13\n\x11_north_rate_errorB\x10\n\x0e_up_rate_error\"\xdc\x01\n\x10\x45NUVelocityUnits\x12U\n\x15\x65\x61st_north_rate_units\x18\x01 \x01(\x0e\x32).sapient_msg.bsi_flex_335_v1_0.SpeedUnitsB\x06\x8a\xb5\x18\x02\x08\x01H\x00\x88\x01\x01\x12\x45\n\rup_rate_units\x18\x02 \x01(\x0e\x32).sapient_msg.bsi_flex_335_v1_0.SpeedUnitsH\x01\x88\x01\x01\x42\x18\n\x16_east_north_rate_unitsB\x10\n\x0e_up_rate_units*^\n\nSpeedUnits\x12\x1b\n\x17SPEED_UNITS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSPEED_UNITS_MS\x10\x01\x12\x13\n\x0fSPEED_UNITS_KPH\x10\x02\"\x04\x08\x03\x10\x03\"\x04\x08\x04\x10\x04\x42,\n\x19\x63om.sapient.common.protosB\rSAPIENTCommonP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.velocity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.sapient.common.protosB\rSAPIENTCommonP\001'
  _globals['_ENUVELOCITY'].fields_by_name['east_rate']._options = None
  _globals['_ENUVELOCITY'].fields_by_name['east_rate']._serialized_options = b'\212\265\030\005\010\001\"\001X'
  _globals['_ENUVELOCITY'].fields_by_name['north_rate']._options = None
  _globals['_ENUVELOCITY'].fields_by_name['north_rate']._serialized_options = b'\212\265\030\005\010\001\"\001Y'
  _globals['_ENUVELOCITY'].fields_by_name['up_rate']._options = None
  _globals['_ENUVELOCITY'].fields_by_name['up_rate']._serialized_options = b'\212\265\030\003\"\001Z'
  _globals['_ENUVELOCITY'].fields_by_name['east_rate_error']._options = None
  _globals['_ENUVELOCITY'].fields_by_name['east_rate_error']._serialized_options = b'\212\265\030\004\"\002eX'
  _globals['_ENUVELOCITY'].fields_by_name['north_rate_error']._options = None
  _globals['_ENUVELOCITY'].fields_by_name['north_rate_error']._serialized_options = b'\212\265\030\004\"\002eY'
  _globals['_ENUVELOCITY'].fields_by_name['up_rate_error']._options = None
  _globals['_ENUVELOCITY'].fields_by_name['up_rate_error']._serialized_options = b'\212\265\030\004\"\002eZ'
  _globals['_ENUVELOCITYUNITS'].fields_by_name['east_north_rate_units']._options = None
  _globals['_ENUVELOCITYUNITS'].fields_by_name['east_north_rate_units']._serialized_options = b'\212\265\030\002\010\001'
  _globals['_SPEEDUNITS']._serialized_start=672
  _globals['_SPEEDUNITS']._serialized_end=766
  _globals['_ENUVELOCITY']._serialized_start=113
  _globals['_ENUVELOCITY']._serialized_end=447
  _globals['_ENUVELOCITYUNITS']._serialized_start=450
  _globals['_ENUVELOCITYUNITS']._serialized_end=670
# @@protoc_insertion_point(module_scope)
