stages:
    - lint
    - unit_test

variables:
  GIT_DEPTH: 2
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/cache/pre-commit"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/cache/poetry/cache"
  POETRY_HOME: "$CI_PROJECT_DIR/cache/poetry/home"
  GIT_SSL_NO_VERIFY: "true"

  # By default set to 'runai-shared-cpu' in dev-git1.dev.local/groups/capabilities/-/settings/ci_cd
  # This can be changed in case of a run:ai system failure
  DEFAULT_RUNNER: $DEFAULT_RUNNER

cache:
  paths: [ $CI_PROJECT_DIR/cache ]


Windows Precommit Checks:
    stage: lint
    tags: [ windows ]
    before_script:
        - pip install pre-commit
    script:
        - pre-commit run --all
    cache:
      paths: [ $PRE_COMMIT_HOME ]

Windows Testing:
    stage: unit_test
    tags: [ windows ]
    before_script:
        - pip install poetry
        - poetry install --sync
    script:
        - poetry run pytest --junitxml=pytest_report.xml
    artifacts:
        when: always
        paths:
          - pytest_report.xml
        reports:
            junit: pytest_report.xml


Unix Testing:
    stage: unit_test
    tags:
    - docker
    image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:26.0.2-cli@sha256:9b65b01f62284b489fffb15421ff547185290a66ef6ae6456bd7d97fe1f06b3c
    services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:26.0.2-dind@sha256:f95f0b3931e90bd65ec7542af140f72371f65dad1044e325ff04016e34db3b96
      alias: dindhost
    before_script:
      - docker info
    script:
        - cd tests
        - docker compose --file docker-compose.yml --file docker-compose.test.yml run --rm unit-tests
        - docker compose down -v
    artifacts:
        when: always
        paths:
          - tests/pytest_report.xml
        reports:
            junit: tests/pytest_report.xml
    retry: 2 # Tests are flaky so retry twice
