# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v2_0/error.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)sapient_msg/bsi_flex_335_v2_0/error.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"L\n\x05\x45rror\x12\x1b\n\x06packet\x18\x01 \x01(\x0c\x42\x06\x8a\xb5\x18\x02\x08\x01H\x00\x88\x01\x01\x12\x15\n\rerror_message\x18\x03 \x03(\tB\t\n\x07_packetJ\x04\x08\x02\x10\x03\x42\x33\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\nErrorProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v2_0.error_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\nErrorProtoP\001'
  _globals['_ERROR'].fields_by_name['packet']._options = None
  _globals['_ERROR'].fields_by_name['packet']._serialized_options = b'\212\265\030\002\010\001'
  _globals['_ERROR']._serialized_start=109
  _globals['_ERROR']._serialized_end=185
# @@protoc_insertion_point(module_scope)
