# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v1_0/alert_ack.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-sapient_msg/bsi_flex_335_v1_0/alert_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\x1a\x1fsapient_msg/proto_options.proto\"\xc0\x02\n\x08\x41lertAck\x12\x1f\n\x08\x61lert_id\x18\x01 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01\x10\x01H\x00\x88\x01\x01\x12V\n\x0c\x61lert_status\x18\x02 \x01(\x0e\x32\x33.sapient_msg.bsi_flex_335_v1_0.AlertAck.AlertStatusB\x06\x8a\xb5\x18\x02\x08\x01H\x01\x88\x01\x01\x12\x13\n\x06reason\x18\x03 \x01(\tH\x02\x88\x01\x01\"}\n\x0b\x41lertStatus\x12\x1c\n\x18\x41LERT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41LERT_STATUS_ACCEPTED\x10\x01\x12\x19\n\x15\x41LERT_STATUS_REJECTED\x10\x02\x12\x1a\n\x16\x41LERT_STATUS_CANCELLED\x10\x03\x42\x0b\n\t_alert_idB\x0f\n\r_alert_statusB\t\n\x07_reasonB)\n\x16uk.gov.dstl.sapientmsgB\rAlertAckProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.alert_ack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026uk.gov.dstl.sapientmsgB\rAlertAckProtoP\001'
  _globals['_ALERTACK'].fields_by_name['alert_id']._options = None
  _globals['_ALERTACK'].fields_by_name['alert_id']._serialized_options = b'\212\265\030\004\010\001\020\001'
  _globals['_ALERTACK'].fields_by_name['alert_status']._options = None
  _globals['_ALERTACK'].fields_by_name['alert_status']._serialized_options = b'\212\265\030\002\010\001'
  _globals['_ALERTACK']._serialized_start=114
  _globals['_ALERTACK']._serialized_end=434
  _globals['_ALERTACK_ALERTSTATUS']._serialized_start=268
  _globals['_ALERTACK_ALERTSTATUS']._serialized_end=393
# @@protoc_insertion_point(module_scope)
