# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v2_0/alert_ack.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-sapient_msg/bsi_flex_335_v2_0/alert_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"\xdb\x02\n\x08\x41lertAck\x12\x1f\n\x08\x61lert_id\x18\x01 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01\x10\x01H\x00\x88\x01\x01\x12\x0e\n\x06reason\x18\x04 \x03(\t\x12]\n\x10\x61lert_ack_status\x18\x05 \x01(\x0e\x32\x36.sapient_msg.bsi_flex_335_v2_0.AlertAck.AlertAckStatusB\x06\x8a\xb5\x18\x02\x08\x01H\x01\x88\x01\x01\"\x90\x01\n\x0e\x41lertAckStatus\x12 \n\x1c\x41LERT_ACK_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x41LERT_ACK_STATUS_ACCEPTED\x10\x01\x12\x1d\n\x19\x41LERT_ACK_STATUS_REJECTED\x10\x02\x12\x1e\n\x1a\x41LERT_ACK_STATUS_CANCELLED\x10\x03\x42\x0b\n\t_alert_idB\x13\n\x11_alert_ack_statusJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\x42\x36\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\rAlertAckProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v2_0.alert_ack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\rAlertAckProtoP\001'
  _globals['_ALERTACK'].fields_by_name['alert_id']._options = None
  _globals['_ALERTACK'].fields_by_name['alert_id']._serialized_options = b'\212\265\030\004\010\001\020\001'
  _globals['_ALERTACK'].fields_by_name['alert_ack_status']._options = None
  _globals['_ALERTACK'].fields_by_name['alert_ack_status']._serialized_options = b'\212\265\030\002\010\001'
  _globals['_ALERTACK']._serialized_start=114
  _globals['_ALERTACK']._serialized_end=461
  _globals['_ALERTACK_ALERTACKSTATUS']._serialized_start=271
  _globals['_ALERTACK_ALERTACKSTATUS']._serialized_end=415
# @@protoc_insertion_point(module_scope)
