# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v2_0/follow.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*sapient_msg/bsi_flex_335_v2_0/follow.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fsapient_msg/proto_options.proto\"0\n\x0c\x46ollowObject\x12 \n\x10\x66ollow_object_id\x18\x01 \x01(\tB\x06\x8a\xb5\x18\x02\x08\x01\x42\x34\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\x0b\x46ollowProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v2_0.follow_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\013FollowProtoP\001'
  _globals['_FOLLOWOBJECT'].fields_by_name['follow_object_id']._options = None
  _globals['_FOLLOWOBJECT'].fields_by_name['follow_object_id']._serialized_options = b'\212\265\030\002\010\001'
  _globals['_FOLLOWOBJECT']._serialized_start=110
  _globals['_FOLLOWOBJECT']._serialized_end=158
# @@protoc_insertion_point(module_scope)
