# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v2_0/task_ack.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg.bsi_flex_335_v2_0 import associated_file_pb2 as sapient__msg_dot_bsi__flex__335__v2__0_dot_associated__file__pb2
from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sapient_msg/bsi_flex_335_v2_0/task_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x33sapient_msg/bsi_flex_335_v2_0/associated_file.proto\x1a\x1fsapient_msg/proto_options.proto\"\xa4\x03\n\x07TaskAck\x12\x1e\n\x07task_id\x18\x01 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01\x10\x01H\x00\x88\x01\x01\x12S\n\x0btask_status\x18\x02 \x01(\x0e\x32\x31.sapient_msg.bsi_flex_335_v2_0.TaskAck.TaskStatusB\x06\x8a\xb5\x18\x02\x08\x01H\x01\x88\x01\x01\x12K\n\x0f\x61ssociated_file\x18\x04 \x01(\x0b\x32-.sapient_msg.bsi_flex_335_v2_0.AssociatedFileH\x02\x88\x01\x01\x12\x0e\n\x06reason\x18\x05 \x03(\t\"\x90\x01\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14TASK_STATUS_ACCEPTED\x10\x01\x12\x18\n\x14TASK_STATUS_REJECTED\x10\x02\x12\x19\n\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n\x12TASK_STATUS_FAILED\x10\x04\x42\n\n\x08_task_idB\x0e\n\x0c_task_statusB\x12\n\x10_associated_fileJ\x04\x08\x03\x10\x04\x42\x35\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\x0cTaskAckProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v2_0.task_ack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\014TaskAckProtoP\001'
  _globals['_TASKACK'].fields_by_name['task_id']._options = None
  _globals['_TASKACK'].fields_by_name['task_id']._serialized_options = b'\212\265\030\004\010\001\020\001'
  _globals['_TASKACK'].fields_by_name['task_status']._options = None
  _globals['_TASKACK'].fields_by_name['task_status']._serialized_options = b'\212\265\030\002\010\001'
  _globals['_TASKACK']._serialized_start=166
  _globals['_TASKACK']._serialized_end=586
  _globals['_TASKACK_TASKSTATUS']._serialized_start=388
  _globals['_TASKACK_TASKSTATUS']._serialized_end=532
# @@protoc_insertion_point(module_scope)
