# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sapient_msg/bsi_flex_335_v2_0/associated_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8sapient_msg/bsi_flex_335_v2_0/associated_detection.proto\x12\x1dsapient_msg.bsi_flex_335_v2_0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fsapient_msg/proto_options.proto\"\x9b\x02\n\x13\x41ssociatedDetection\x12\x32\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x1e\n\x07node_id\x18\x02 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01\x18\x01H\x01\x88\x01\x01\x12 \n\tobject_id\x18\x03 \x01(\tB\x08\x8a\xb5\x18\x04\x08\x01\x10\x01H\x02\x88\x01\x01\x12Q\n\x10\x61ssociation_type\x18\x04 \x01(\x0e\x32\x32.sapient_msg.bsi_flex_335_v2_0.AssociationRelationH\x03\x88\x01\x01\x42\x0c\n\n_timestampB\n\n\x08_node_idB\x0c\n\n_object_idB\x13\n\x11_association_type*\xc4\x01\n\x13\x41ssociationRelation\x12$\n ASSOCIATION_RELATION_UNSPECIFIED\x10\x00\x12$\n ASSOCIATION_RELATION_NO_RELATION\x10\x01\x12\x1f\n\x1b\x41SSOCIATION_RELATION_PARENT\x10\x02\x12\x1e\n\x1a\x41SSOCIATION_RELATION_CHILD\x10\x03\x12 \n\x1c\x41SSOCIATION_RELATION_SIBLING\x10\x04\x42\x41\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\x18\x41ssociatedDetectionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v2_0.associated_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v2B\030AssociatedDetectionProtoP\001'
  _globals['_ASSOCIATEDDETECTION'].fields_by_name['node_id']._options = None
  _globals['_ASSOCIATEDDETECTION'].fields_by_name['node_id']._serialized_options = b'\212\265\030\004\010\001\030\001'
  _globals['_ASSOCIATEDDETECTION'].fields_by_name['object_id']._options = None
  _globals['_ASSOCIATEDDETECTION'].fields_by_name['object_id']._serialized_options = b'\212\265\030\004\010\001\020\001'
  _globals['_ASSOCIATIONRELATION']._serialized_start=444
  _globals['_ASSOCIATIONRELATION']._serialized_end=640
  _globals['_ASSOCIATEDDETECTION']._serialized_start=158
  _globals['_ASSOCIATEDDETECTION']._serialized_end=441
# @@protoc_insertion_point(module_scope)
